apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: server
          name: server
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 256Mi
              cpu: 128m
          startupProbe:
            httpGet:
              path: /healthz-with-db
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 1
          env:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: server

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: server
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server
  annotations:
    nginx.org/websocket-services: "server"
spec:
  ingressClassName: "nginx"
  rules:
    - host: server
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: server
                port:
                  number: 80
