apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/pre
images:
  - name: server
    newName: server
    newTag: v0.0.0
patchesStrategicMerge:
  - |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: migration
    spec:
      template:
        spec:
          containers:
            - name: server
              envFrom:
                - prefix: db_
                  secretRef:
                    name: pgo-cluster-pguser-example-production
