FROM node:18-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci
COPY . ./
RUN npm run client:build

FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/ /app/dist

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
