encryptionsalt: v1:8ERTHHUW39s=:v1:5DvxTt4NQYAXWUq1:lJIwrChHacx1YFEGCWrbYuXzUEGq1A==
config:
  gcp:project: cheap-k8s-dev
  gcp:region: us-central1
  cheap-k8s-example-infra:githubToken:
    secure: v1:MvYaNTYDxPY1ncRn:vcLfyjpo1WIsg/sdrgVdaX0LCGPHY/C9hwL5mEyb+VghlrGkFzLX08hG+eR2a0vTJ6CCMP5I6xY=
  cheap-k8s-example-infra:nodesPerZone: "2"
