apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
        - name: server
          image: server
          command: ["npm", "run", "server:migrate"]
      restartPolicy: Never
