apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/pre
images:
  - name: server
    newName: us-central1-docker.pkg.dev/cheap-k8s-dev/example/server
    newTag: v0.1.1-20230403-043142utc
patchesStrategicMerge:
  - |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: migration
    spec:
      template:
        spec:
          containers:
            - name: server
              envFrom:
                - prefix: db_
                  secretRef:
                    name: pgo-cluster-pguser-example-staging
